Vagrant.configure("2") do |config|

  # -----------------------------
  # web01 - Ubuntu 20.04
  # -----------------------------
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"

    web01.vm.provider "virtualbox" do |vb|
      vb.name = "web01"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # -----------------------------
  # web02 - Ubuntu 20.04
  # -----------------------------
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.12"

    web02.vm.provider "virtualbox" do |vb|
      vb.name = "web02-new"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # -----------------------------
  # db01 - CentOS 7
  # -----------------------------
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.13"

    db01.vm.provider "virtualbox" do |vb|
      vb.name = "db01"
      vb.memory = 1024
      vb.cpus = 1
    end

    db01.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/^mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/CentOS-Base.repo
      sudo sed -i 's|^#baseurl=http://mirror.centos.org/centos/$releasever|baseurl=http://vault.centos.org/7.9.2009|g' /etc/yum.repos.d/CentOS-Base.repo

      sudo yum clean all
      sudo yum makecache
      sudo yum install -y mariadb-server
      sudo systemctl enable mariadb
      sudo systemctl start mariadb

      echo "db01 provisioning completed" | sudo tee /home/vagrant/db01-setup.txt
    SHELL
  end

end