# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Keep only one simple network for now
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos-stream-9-test"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf -y update
    dnf -y install httpd

    systemctl enable --now httpd
    systemctl disable --now firewalld || true

    mkdir -p /var/www/html
    echo "Hello World from Vagrant" > /var/www/html/index.html
  SHELL
end